service: websocket-el-chat

configValidationMode: error

plugins:
  - serverless-offline
  - serverless-webpack

custom:
  webpack:
    webpackConfig: ./webpack.config.js
    includeModules: true
  dynamodb:
    stages:
      - dev
      - local
    start:
      port: 8000
      inMemory: true
      migrate: true
  prune:
    automatic: true
    number: 3

provider:
  name: aws
  runtime: nodejs14.x
  region: us-east-1
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:*
          Resource: "arn:aws:dynamodb:us-east-1:*:table/appointments-typescript-test"
  lambdaHashingVersion: 20201221

functions:

resources:
  Resources:
    dbAppointment:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: appointments-typescript-test
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH